version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: aerowaste_backend
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - postgres
    environment:
      MONGO_URI: mongodb://mongo:27017/aero_waste
      POSTGRES_HOST: postgres
      POSTGRES_DB: aerowaste
      POSTGRES_USER: aerowaste_user
      POSTGRES_PASSWORD: J3nm1aru8y
    volumes:
      - ./app:/app  # Optional: enables live code updates if you change code locally

  mongo:
    image: mongo:6.0
    container_name: aerowaste_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgis/postgis:16-3.4
    container_name: aerowaste_postgres
    restart: always
    environment:
      POSTGRES_DB: aerowaste
      POSTGRES_USER: aerowaste_user
      POSTGRES_PASSWORD: J3nm1aru8y
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aerowaste_user -d aerowaste"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  postgres_data: